/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as Plan_formacionIndexRouteImport } from './routes/plan_formacion/index'
import { Route as PersonaIndexRouteImport } from './routes/persona/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const Plan_formacionIndexRoute = Plan_formacionIndexRouteImport.update({
  id: '/plan_formacion/',
  path: '/plan_formacion/',
  getParentRoute: () => rootRouteImport,
} as any)
const PersonaIndexRoute = PersonaIndexRouteImport.update({
  id: '/persona/',
  path: '/persona/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/persona': typeof PersonaIndexRoute
  '/plan_formacion': typeof Plan_formacionIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/persona': typeof PersonaIndexRoute
  '/plan_formacion': typeof Plan_formacionIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/persona/': typeof PersonaIndexRoute
  '/plan_formacion/': typeof Plan_formacionIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/persona' | '/plan_formacion'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/persona' | '/plan_formacion'
  id: '__root__' | '/' | '/persona/' | '/plan_formacion/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PersonaIndexRoute: typeof PersonaIndexRoute
  Plan_formacionIndexRoute: typeof Plan_formacionIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/plan_formacion/': {
      id: '/plan_formacion/'
      path: '/plan_formacion'
      fullPath: '/plan_formacion'
      preLoaderRoute: typeof Plan_formacionIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/persona/': {
      id: '/persona/'
      path: '/persona'
      fullPath: '/persona'
      preLoaderRoute: typeof PersonaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PersonaIndexRoute: PersonaIndexRoute,
  Plan_formacionIndexRoute: Plan_formacionIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
